### ISSUE TITLE
Pregenerated bindings for `riscv64gc-unknown-linux-musl`

### ISSUE THREAD

**Issue by stefansundin** [aws/aws-lc-rs#874]
### Problem:

Now that riscv64 is becoming more popular, I want to start providing riscv64 docker images for my rust projects.

I noticed that support for `riscv64gc-unknown-linux-gnu` was already added in https://github.com/aws/aws-lc-rs/commit/b99c66101b0c132ca7f6ccbe756a7721f0106312, but I want to use `musl`.

aws-lc-sys is failing compilation with this error:

```
#13 125.9 error: failed to run custom build command for `aws-lc-sys v0.30.0`
#13 125.9 note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE-BUILD_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.
#13 125.9
#13 125.9 Caused by:
#13 125.9   process didn't exit successfully: `/igloo/target/release-build/build/aws-lc-sys-2b0d478e5e84b768/build-script-main` (exit status: 101)
#13 125.9   --- stdout
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREFIX
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_PREGENERATING_BINDINGS
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_EXTERNAL_BINDGEN
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_ASM
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CFLAGS
#13 125.9   cargo:rerun-if-env-changed=CFLAGS_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=CFLAGS
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_PREBUILT_NASM
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_C_STD
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_BUILDER
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREGENERATED_SRC_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_NO_PREGENERATED_SRC
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_EFFECTIVE_TARGET_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_EFFECTIVE_TARGET
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_STATIC
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=AWS_LC_SYS_CMAKE
#13 125.9   cargo:rerun-if-env-changed=CMAKE_riscv64gc_unknown_linux_musl
#13 125.9   cargo:rerun-if-env-changed=CMAKE
#13 125.9
#13 125.9   --- stderr
#13 125.9   Missing dependency: cmake
#13 125.9
#13 125.9   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.30.0/builder/main.rs:463:40:
#13 125.9   called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
#13 125.9   stack backtrace:
#13 125.9      0:     0x55555561acd6 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h1864d000ac8e40da
#13 125.9      1:     0x55555563c8d0 - <unknown>
#13 125.9      2:     0x555555616f14 - <unknown>
#13 125.9      3:     0x55555561ab7c - <unknown>
#13 125.9      4:     0x55555561c77e - <unknown>
#13 125.9      5:     0x55555561c5a4 - <unknown>
#13 125.9      6:     0x55555561cff0 - <unknown>
#13 125.9      7:     0x55555561cdec - <unknown>
#13 125.9      8:     0x55555561b124 - <unknown>
#13 125.9      9:     0x55555561cacc - <unknown>
#13 125.9     10:     0x55555557bce4 - <unknown>
#13 125.9     11:     0x55555557c040 - <unknown>
#13 125.9     12:     0x555555581d56 - <unknown>
#13 125.9     13:     0x555555582d22 - <unknown>
#13 125.9     14:     0x55555558d24a - <unknown>
#13 125.9     15:     0x55555558d16c - <unknown>
#13 125.9     16:     0x555555585ffe - <unknown>
#13 125.9     17:     0x555555610962 - <unknown>
#13 125.9     18:     0x555555585fea - <unknown>
#13 125.9     19:     0x5555555852f6 - main
#13 125.9     20:     0x2aaaab31d99c - <unknown>
#13 125.9     21:     0x2aaaab31da44 - __libc_start_main
#13 125.9     22:     0x55555557c48c - <unknown>
#13 125.9     23:                0x0 - <unknown>
```

I changed my target to `riscv64gc-unknown-linux-gnu` and it now builds, but it doesn't run since my docker image doesn't have any files other than my binary.

If I understand it correctly, I think something similar to https://github.com/aws/aws-lc-rs/commit/b99c66101b0c132ca7f6ccbe756a7721f0106312 needs to be changed, but for `musl` and not `gnu`. Both `aarch64` and `x86_64` have both `gnu` and `musl` variants.

I also noticed that `riscv64gc-unknown-linux-gnu` was **not** added to the list of pregenerated bindings in `aws-lc-sys/README.md`.

#### Relevant details
AWS-LC for Rust versions or commit: using latest crate versions published

System information: I'm cross-compiling from a macbook.

```
$ docker run -it --platform=linux/riscv64 rust:1-trixie uname -srvmp
Linux 6.10.14-linuxkit #1 SMP Thu Aug 14 19:26:13 UTC 2025 riscv64 unknown
```

Thanks!

**Comment by justsmth** [comment]
Hello! We just released [aws-lc-rs v1.15.0](https://github.com/aws/aws-lc-rs/releases), which provides universal bindings, eliminating the need for bindings generation for most users.

This issue will now be closed. Feel free to comment here, or open another issue if you continue to have problems after upgrading. Thanks for reporting and helping us improve our library! 😃

**Comment by stefansundin** [comment]
Hello @justsmth. I just got the chance to try this and I am still experiencing issues building riscv64 with aws-lc-rs v1.15.0 and aws-lc-sys v0.33.0.

```
#9 73.99   Missing dependency: cmake
#9 73.99
#9 73.99   thread 'main' (736) panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/aws-lc-sys-0.33.0/builder/main.rs:475:40:
#9 73.99   called `Result::unwrap()` on an `Err` value: "Required build dependency is missing. Halting build."
```

I created a small repository that can reproduce the problem. Full output from the build is available in the README as well: https://github.com/stefansundin/aws-lc-sys-riscv64-build-issue-repro

The repository builds successfully for arm64 and amd64.
